### ISSUE TITLE
disconnected from codeium server 

### ISSUE THREAD

**Issue by lhw123-max** [Exafunction/CodeiumJetBrains#25]
webstrom  plugin disconnected from codeium server,

**Comment by fortenforge** [comment]
You probably need to update your version of Codeium to the latest. If you don't see a newer update of Codeium you might need to update webstorm itself.

**Comment by lhw123-max** [comment]
My Codeium version is 1.2.61 and my Webstorm version is 2021.2.2,Before that, it could be used normally. Do I need to update the webstorm version now?




淘宝网
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Exafunction/CodeiumJetBrains"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月16日(星期二) 凌晨1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Exafunction/CodeiumJetBrains] disconnected from codeium server  (Issue #25)





 
You probably need to update your version of Codeium to the latest. If you don't see a newer update of Codeium you might need to update webstorm itself.

**Comment by fortenforge** [comment]
Yes. We recently made a change that no longer supports older Codeium versions. Unfortunately, you'll also need to update WebStorm since later versions of the Codeium WebStorm plugin only support later versions of WebStorm.

**Comment by lhw123-max** [comment]
Excuse me, what is the minimum version required for webstorm to use Codeium？&nbsp;


淘宝网
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rahul ***@***.***&gt;; 
发送时间: 2024年4月16日(星期二) 上午9:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Exafunction/CodeiumJetBrains] disconnected from codeium server  (Issue #25)














 
Yes. We recently made a change that no longer supports older Codeium versions. Unfortunately, you'll also need to update WebStorm since later versions of the Codeium WebStorm plugin only support later versions of WebStorm.

**Comment by fortenforge** [comment]
2022.3

**Comment by lhw123-max** [comment]
Thank you&nbsp;


淘宝网
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rahul ***@***.***&gt;; 
发送时间: 2024年4月16日(星期二) 上午10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Exafunction/CodeiumJetBrains] disconnected from codeium server  (Issue #25)














 
2022.3

**Comment by Algomorph** [comment]
I'm also seeing "Disconnected from Codeium Server" on Clion 2024.2.2 w/ Codeium 1.16.13 on a Teams plan (latest versions at time of post).
No combination of uninstalling, deleting `$HOME/.condeium` folder, re-logging in fixes this.
Inlay hints / autocomplete not working.

CLion log:
[idea.log](https://github.com/user-attachments/files/17059957/idea.log)

Codeium diagnostics (from "Download Diagnostics"):
[Codeium_Diagnostics.log](https://github.com/user-attachments/files/17059972/Codeium_Diagnostics.log)

**Comment by hakanngul** [comment]
are they don't have any solutions about this problems?

**Comment by Algomorph** [comment]
@hakanngul only workaround for now AFAIK is to downgrade, see https://github.com/Exafunction/CodeiumJetBrains/issues/40#issuecomment-2373104070. The maintainers have reached out to me, saying they're working on it, two days ago.

**Comment by fortenforge** [comment]
Version 1.20.2 (released yesterday) should fix this.

**Comment by ZerGo0** [comment]
> Version 1.20.2 (released yesterday) should fix this.

It worked for a few auto completions for me, and then it stopped working again. Restarting the IDE didn't fix it, and it just stopped working entirely again.

**Comment by fortenforge** [comment]
Can you share logs? ("Download Diagnostics")

**Comment by ZerGo0** [comment]
> Can you share logs? ("Download Diagnostics")

Thanks for the quick response, here you go:
[Codeium_1.json](https://github.com/user-attachments/files/17169107/Codeium_1.json)

I guess it has issues finding the actual file?
Here are the paths:
Absolute: C:/DevGit/Shopsystem/Shared/Core/REDACTED/ApiClient/ApiClient.cs
From Solution Root: ApiClient/ApiClient.cs
From Repo Root: Shared/Core/REDACTED/ApiClient/ApiClient.cs

It actually works in some projects, but it doesn't work in this one.

**Comment by Algomorph** [comment]
> Version 1.20.2 (released yesterday) should fix this.

It doesn't for me.

**Comment by Algomorph** [comment]
`1.20.4` Fixes the issue for me.

**Comment by fortenforge** [comment]
Oh yes, forgot to update this but 1.20.4 has the fix for this. Thanks for everyones help in sharing the logs with me!
